CREATE TABLE IF NOT EXISTS "public"."persona_holder_chat_messages" (
  "id" bigint NOT NULL,
  "sender" "text" NOT NULL,
  "content" "text",
  "rich" "jsonb",
  "ip_address" "inet" NOT NULL,
  "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
  "is_edited" boolean
);

ALTER TABLE "public"."persona_holder_chat_messages" OWNER TO "postgres";
ALTER TABLE "public"."persona_holder_chat_messages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."persona_holder_chat_messages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."persona_holder_chat_messages"
    ADD CONSTRAINT "persona_holder_chat_messages_pkey" PRIMARY KEY ("id");

ALTER TABLE "public"."persona_holder_chat_messages" ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE "public"."persona_holder_chat_messages" TO "anon";
GRANT ALL ON TABLE "public"."persona_holder_chat_messages" TO "authenticated";
GRANT ALL ON TABLE "public"."persona_holder_chat_messages" TO "service_role";

GRANT ALL ON SEQUENCE "public"."persona_holder_chat_messages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."persona_holder_chat_messages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."persona_holder_chat_messages_id_seq" TO "service_role";

CREATE POLICY "Allow read access for all users" ON public.persona_holder_chat_messages FOR SELECT USING (true);

CREATE POLICY "Allow update for message owner" ON public.persona_holder_chat_messages FOR UPDATE
USING (sender = ("auth"."jwt"() ->> 'wallet_address'::text))
WITH CHECK (
  (
    ("content" IS NOT NULL AND "content" != '' AND length("content") <= 1000)
    OR
    ("content" IS NULL AND "rich" IS NOT NULL)
  )
);

CREATE POLICY "Allow delete for message owner" ON public.persona_holder_chat_messages FOR DELETE
USING (sender = ("auth"."jwt"() ->> 'wallet_address'::text));
